# Generated by Django 5.2.1 on 2025-06-05 16:06

import django.core.validators
import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('is_trailer', models.BooleanField(default=False)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('license_type', models.CharField(blank=True, max_length=50)),
                ('license_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('category', models.CharField(choices=[('New on Videoflix', 'New on Videoflix'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Romance', 'Romance')], default='New on Videoflix', max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=videos.models.video_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv', 'm4v'])])),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_variants', models.JSONField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=videos.models.thumb_upload_to)),
                ('hero_frame', models.ImageField(blank=True, null=True, upload_to=videos.models.hero_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='videos_vide_created_f7522a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'ordering': ('-updated',),
                'indexes': [models.Index(fields=['user', 'video'], name='videos_watc_user_id_501f95_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
