# Generated by Django 5.2 on 2025-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('New on Videoflix', 'New on Videoflix'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Romance', 'Romance')], default='New on Videoflix', max_length=30),
        ),
        migrations.AddField(
            model_name='video',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='director',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='license_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='license_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
