# Generated by Django 5.2.1 on 2025-06-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Romance', 'Romance')], default='Action', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='director',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
