# Generated by Django 5.2.1 on 2025-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchprogress',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
