# Generated by Django 5.2 on 2025-05-15 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_hls_path_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hero_frame',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_variants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, help_text='Automatisch generiertes Standbild für Listen-Thumbnail', null=True, upload_to='thumbs/'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv', 'm4v'])]),
        ),
    ]
