# Generated by Django 5.2 on 2025-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_hero_frame_video_source_variants_video_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
