# Generated by Django 5.2 on 2025-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_path',
        ),
        migrations.AlterField(
            model_name='video',
            name='hero_frame',
            field=models.ImageField(blank=True, help_text='Großes Poster-Bild (1280 px)', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Pfad zur bevorzugten MP4-Datei (z. B. 720 p)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_variants',
            field=models.JSONField(blank=True, help_text='MP4-Varianten (1080/720/360/240 p) als JSON-Liste', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, help_text='Automatisch generiertes Thumbnail (320 px)', null=True, upload_to='thumbs/'),
        ),
    ]
