# Generated by Django 5.2 on 2025-05-16 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_hls_path_alter_video_hero_frame_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, help_text='Pfad zur bevorzugten MP4-Datei (z. B. 720 p)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'ordering': ('-updated',),
                'unique_together': {('user', 'video')},
            },
        ),
    ]
