# Generated by Django 5.2 on 2025-05-16 10:55

import django.core.validators
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_source_url_watchprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hero_frame',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.hero_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='license_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_variants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.thumb_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=videos.models.video_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv', 'm4v'])]),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='videos_vide_created_f7522a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['user', 'video'], name='videos_watc_user_id_501f95_idx'),
        ),
    ]
