# Generated by Django 5.2 on 2025-05-09 08:24

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
