# .github/workflows/backend-ci.yml
name: 🧪 Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: videoflix_ci
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U test -d videoflix_ci"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:                           # ← globale Umgebungs­variablen für alle Steps
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}   # kommt aus GitHub-Secrets
      DEBUG: "False"

      # Django liest DATABASE_URL – darum reicht 1 Variable:
      DATABASE_URL: postgres://test:test@localhost:5432/videoflix_ci
     
      DB_NAME: videoflix_ci
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: localhost        # Service-Hostname
      DB_PORT: "5432"

      DJANGO_SETTINGS_MODULE: video_backend.settings

    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test --verbosity 2
