# .github/workflows/deployment.yml
name: 🌐 Remote Deploy (Docker Compose)

on:
  push:
    branches: [ "main" ]            # Deploys nur von main

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      # nur zum Loggen (nicht unbedingt nötig)

      - name: 🚀 SSH & Docker Compose deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}     # z. B. vps.example.com
          username: ${{ secrets.SSH_USER }}     # z. B. ubuntu
          key:      ${{ secrets.SSH_KEY }}      # privater Deploy-Key
          port:     ${{ secrets.SSH_PORT }}     # Standard 22
          script: |
            set -e
            echo "› we are on $(hostname) – pulling latest code"
            cd /opt/videoflix_backend               # ← dein Projektordner auf dem Server
            git fetch --all
            git reset --hard origin/main

            echo "› pulling base images (if any)"
            docker compose pull                     # zieht neue Images aus Registry

            echo "› rebuilding / restarting containers"
            docker compose up -d --build            # baut Images neu & startet Container

            echo "✅ deploy complete"

