name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    strategy:
      matrix:
        python-version: [3.11, 3.12]   # 3.7 entfernt, moderne Versionen hinzugefügt

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4         # v4 ist die aktuelle Major-Version
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
